Add support for image module and external inference services
semi-technologies/weaviate-helm pull request #43
Opened 2021-05-09 20:12 UTC by antas-marcin

Closes #41 
Closes #42

2021-05-11 11:25 UTC, etiennedi requested changes

2021-05-11 11:25 UTC, etiennedi commented on weaviate/templates/weaviateStatefulset.yaml
> +          - name: IMAGE_VECTORIZER_URL
update to `IMAGE_INFERENCE_API`

2021-05-13 07:39 UTC, antas-marcin commented on weaviate/templates/weaviateStatefulset.yaml
> +          - name: IMAGE_VECTORIZER_URL
done

2021-05-13 08:06 UTC, etiennedi approved these changes

2021-05-13 08:10 UTC, merged